#!/usr/bin/python2.7
def mergeSort(arr):
    if len(arr) == 1:
        return arr, 0
    else:
        a = arr[:(len(arr)//2)]
        b = arr[len(arr)//2:]
        c = []

        a , ai = mergeSort(a)
        b , bi = mergeSort(b)

        i = 0
        j = 0
        inversions = ai + bi + 0

        while i < len(a) and j < len(b):
            if a[i] <= b[j]:
                c.append(a[i])
                i += 1
            else:
                c.append(b[j])
                j += 1
                inversions += (len(a) - i)


        c += a[i:]
        c += b[j:]
        
        return c, inversions

l = list(map(int,raw_input().split()))
l, linversions = mergeSort(l)
print(linversions)


